force-app/main/default/objects/Contact/fields/MonthlyBadgeDiff__c.field-meta.xml
<CustomField>
    <fullName>MonthlyBadgeDiff__c</fullName>
    <formula>CurrMonthTHBadges__c -  PrevMonthTHBadges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Badge Difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MonthlyPointDiff__c.field-meta.xml
<CustomField>
    <fullName>MonthlyPointDiff__c</fullName>
    <formula>CurrMonthTHPoints__c -  PrevMonthTHPoints__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Point Difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TotalTHBadges__c.field-meta.xml
<CustomField>
    <fullName>TotalTHBadges__c</fullName>
    <label>Total Trail Head Badges</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TotalTHPoints__c.field-meta.xml
<CustomField>
    <fullName>TotalTHPoints__c</fullName>
    <label>Total Trail Head Points</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TrailHeadId__c.field-meta.xml
<CustomField>
    <fullName>TrailHeadId__c</fullName>
    <description>The trail head Id of the contact</description>
    <label>Trail Head Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WeeklyBadgeDiff__c.field-meta.xml
<CustomField>
    <fullName>WeeklyBadgeDiff__c</fullName>
    <formula>CurrWeekTHBadges__c -  PrevWeekTHBadges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weekly Badge Difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WeeklyPointDiff__c.field-meta.xml
<CustomField>
    <fullName>WeeklyPointDiff__c</fullName>
    <formula>CurrWeekTHPoints__c -  PrevWeekTHPoints__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weekly Point Difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TrailHeadController.cls
public class TrailHeadController {
    
    private List<Contact> lstContacts;
    private List<Contact> lstWeekCons;
    private List<Contact> lstMonthCons;
    
    public TrailHeadController(){
        lstContacts = new List<Contact>();
        lstWeekCons = new List<Contact>();
        lstMonthCons = new List<Contact>();
    }
    
    public List<Contact> getListOfContacts(){
        lstContacts = [SELECT Name, TotalTHBadges__c, TotalTHPoints__c FROM Contact WHERE TrailHeadId__c != NULL ORDER BY TotalTHBadges__c DESC NULLS LAST];
        return lstContacts;
    }
    
    public List<Contact> getListOfWeeklyChampions(){
        List<Contact> lstCons = new List<Contact>();
        lstCons = [SELECT Name, WeeklyBadgeDiff__c, WeeklyPointDiff__c FROM Contact WHERE TrailHeadId__c != NULL AND WeeklyBadgeDiff__c != 0 ORDER BY WeeklyBadgeDiff__c DESC];
        if(!lstCons.isEmpty()){
            lstWeekCons.add(lstCons[0]);
            for(Integer i = 1; i<lstCons.size(); i++){
                if(lstWeekCons[0].WeeklyBadgeDiff__c > lstCons[i].WeeklyBadgeDiff__c){
                    break;
                }
                else{
                    if(lstWeekCons[0].WeeklyBadgeDiff__c == lstCons[i].WeeklyBadgeDiff__c){
                        lstWeekCons.add(lstCons[i]);
                    }
                }
            }
        }
        return lstWeekCons;
    }
    
    public List<Contact> getListOfMonthlyChampions(){
        List<Contact> lstCons = new List<Contact>();
        lstCons = [SELECT Name, MonthlyBadgeDiff__c, MonthlyPointDiff__c FROM Contact WHERE TrailHeadId__c != NULL AND MonthlyBadgeDiff__c != 0 ORDER BY MonthlyBadgeDiff__c DESC];
        if(!lstCons.isEmpty()){
            lstMonthCons.add(lstCons[0]);
            for(Integer i = 1; i<lstCons.size(); i++){
                if(lstMonthCons[0].MonthlyBadgeDiff__c > lstCons[i].MonthlyBadgeDiff__c){
                    break;
                }
                else{
                    if(lstMonthCons[0].MonthlyBadgeDiff__c == lstCons[i].MonthlyBadgeDiff__c){
                        lstMonthCons.add(lstCons[i]);
                    }
                }
            }
        }
        return lstMonthCons;
    }
    
}